- topic_name:    "/sim/pose"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name:  "gz.msgs.Odometry"
  direction:     GZ_TO_ROS

- gz_topic_name:  "/x500/command/motor_speed"
  ros_topic_name: "/sim/motor_speed" 
  ros_type_name:  "actuator_msgs/msg/Actuators"
  gz_type_name:   "gz.msgs.Actuators"
  direction:      ROS_TO_GZ
