<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>eredin_host</name>
  <version>0.0.1</version>
  <description>VC1 ROS integration package</description>
  <license>GPL 2.0</license>
  <author     email="danfoot4567@gmail.com">Noe Sanchez</author>
  <maintainer email="danfoot4567@gmail.com">Noe Sanchez</maintainer>

  <build_depend>libclang-dev</build_depend>
  <build_depend>rosidl_runtime_rs</build_depend>
  <depend>rcl</depend>
  <depend>builtin_interfaces</depend>
  <depend>rcl_interfaces</depend>

  <export>
    <build_type>ament_cargo</build_type>
  </export>
</package>
